### ISSUE TITLE
Getting typescript error occurred in typescript task.

### ISSUE THREAD

**Issue by EZotov** [devoooo4u/spfx-task-list-web-part#3]
Getting this error when starting gulp test or gulp serve. Please tell me. What could be the problem?
Typescript have updated but doesn't work.
Packages:
gulp 3.9.1
@microsoft/sp-build-web 1.4.1
node version 10.11

**Comment by devoooo4u** [comment]
It seems to be a version issue.. Try downgrading the LTS version of node - 8.11.3. and try running gulp tasks

**Comment by devoooo4u** [comment]
Closing this as no active threads
