### ISSUE TITLE
InstallGuide - Please

### ISSUE THREAD

**Issue by DrFront** [devoooo4u/spfx-task-list-web-part#4]
Hi!

I´m new to custom application in Sharepoint and really needs to publish an issue-tracking list in to the start site.

Could you help me with an installationguide on this? 
Is it possible to collect lists from another site if I connect it as a Hub-site as well?

**Comment by devoooo4u** [comment]
@DrFront  Steps to fix the issue:

Clone the repository
run npm install
run npm i @microsoft/sp-http@v1.4.1
run npm dedupe
5 And finally, run gulp-serve
