### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by mdev23** [devoooo4u/spfx-task-list-web-part#5]
Provide steps to deploy please, solution does not seem to work. I am unable to build the solution. Getting below message: Message:
    src\webparts\taskList\TaskList.module.scss
Error: File to import not found or unreadable: node_modules/@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss.
        on line 1 of src/webparts/taskList/TaskList.module.scss
>> @import '~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss';

**Comment by devoooo4u** [comment]
Hi @mdev23  Steps to fix the issue:

Clone the repository
run npm install
run npm i @microsoft/sp-http@v1.4.1
run npm dedupe
5 And finally, run gulp-serve
